name = "CircuitCompilation2xn"
uuid = "d7352aab-50d9-4722-a759-d8c586bf890d"
authors = ["Anthony Micciche <amicciche@umass.edu>"]
version = "0.1.0"

[deps]
QuantumClifford = "0525e862-1e90-11e9-3e4d-1b39d7109de1"